### ISSUE TITLE
Cant install curl while deploying models with CRD

### ISSUE THREAD

**Issue by shabashaash** [nekomeowww/ollama-operator#17]
Tried to deploy example phi model on k3s cluster with nvidia drivers, runtime and toolkit installed (also device plugin deployed)
Each node got 1 GPU with 12Gb of vram.
After successfully installing operator and CLI:
```
kubectl apply -f https://raw.githubusercontent.com/nekomeowww/ollama-operator/main/dist/install.yaml
go install github.com/nekomeowww/ollama-operator/cmd/kollama@latest
```

Tried to deploy with following CRD config:
```yaml
apiVersion: ollama.ayaka.io/v1
kind: Model
metadata:
  name: phi-test
spec:
  replicas: 2
  image: phi
  imagePullPolicy: IfNotPresent
  storageClassName: local-path
  resources:
    limits:
      cpu: 4
      memory: 8Gi
      nvidia.com/gpu: 1
    requests:
      cpu: 4
      memory: 8Gi
      nvidia.com/gpu: 1 
```

Pods start to CrashLoop with following logs:
```
sudo kubectl logs ollama-model-phi-test-c5d699b74-xbq87 --all-containers

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package curl
```

Seems like there is the problem with default image or something. Maybe adding **apt update && ...** will help?
Or perhaps container having trouble connecting to internet but other containers work just fine.

Also looks like container is falling at this step:
https://github.com/nekomeowww/ollama-operator/blob/2717e823f4936ff212bd7d11234f67c132741477/pkg/model/pod.go#L83C4-L83C148

**Comment by nekomeowww** [comment]
Fixed, added `apt update &&` and released as `v0.10.0`, but this is still a bit of hard to use. I will implement another dedicated check Job or validator to help to preload the models.

**Comment by shabashaash** [comment]
Thank you!
Curl problem got fixed:
![изображение](https://github.com/user-attachments/assets/bd52c3d5-8d4c-4fb3-9d85-e3acf6390dac)

but now I cant pull 'phi' image for some reason:
![изображение](https://github.com/user-attachments/assets/90b64570-3566-4d7a-8e5e-e7f1632f59db)

Seems like there is something wrong with models-store or with creating a Puller server idk.

Logs of model-store container (idk why it cant find GPU, but nvm):
![изображение](https://github.com/user-attachments/assets/ac48cf5a-9beb-4a97-b44b-cf29a1bb9775)
then all logs are like that:
![изображение](https://github.com/user-attachments/assets/c660f1a7-db24-40fa-ad87-c30d5962404d)


Also when trying to add `runtimeClassName: nvidia` to CRD template: 
```yaml
apiVersion: ollama.ayaka.io/v1
kind: Model
metadata:
  name: phi-test
spec:
  image: phi
  imagePullPolicy: IfNotPresent
  storageClassName: local-path
  RuntimeClassName: nvidia
  resources:
    limits:
      cpu: 4
      memory: 8Gi
      nvidia.com/gpu: 1
    requests:
      cpu: 4
      memory: 8Gi
      nvidia.com/gpu: 1 
EOF
```
I am getting following error:
![изображение](https://github.com/user-attachments/assets/f29ca599-be3a-4eb8-b7c1-f4d54699a914)
_Error from server (BadRequest): error when creating "STDIN": Model in version "v1" cannot be handled as a Model: strict decoding error: unknown field "spec.RuntimeClassName"_

Maybe CRD template got cached somehow or something, but I dont know how to update it.

**Comment by shabashaash** [comment]
Okay so the things I did:

1. Manually deleted everything connected to ollama (operator) from the cluster (StatefulSets, Services, Deployments, PVC, namespaces etc etc)
2. Deleted CRDs, rolebindings and clusterroles
3. Installed operator again 
4. Changed meta: name: from _**phi-test**_ to _**phi**_ in model CRD yaml (I guess this is the one fixed the issue)
And its working!
Is this expected behaviour? I thought _**spec: image:**_ should point to the image of the model, and _**meta: name**:_ is just name of the CRD created

But still sadly cant use new specs (runtimeClassName etc), still thinking that model CRD not updating propertly but I cant figure out how to do it.

**Comment by nekomeowww** [comment]
Ah thanks for pointing that out. And sorry for jamming you for a while to recreate everything, I am sorry for any of the inconveniences caused by the last release, let me check the workflow on my deployed clusters to fix it.

**Comment by shabashaash** [comment]
Thank you again! No problem you doing gods work here!

The problem with name vs image still persists, image-puller tries to pull meta:name and not the spec:image (but its not a big problem)
Sorry to bother you with this questions, but Im quite new to k8s so would greatly appreciate your help.
Do you know what should I do to make ollama-model-* pods schedule on control-plane master nodes as well?
They have no taints, and I guess I should provide custom podTemplate with:
```yaml
spec:
  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/contol-panel"
    operator: "Exists"
    effect: "NoSchedule"
```
but Im getting error stating what I need to provide image for the template (which is expected) so I guess I need to copy full PodTemplate and paste it there with needed settings?

Actually the exact message Im getting is that there are no free nodes with 1 GPU avaliable.
I got 6 PCs each with 1 GPU 5 of which is master-nodes and 1 is agent. When Im trying to deploy 2 models second one getting this error:
![изображение](https://github.com/user-attachments/assets/c06f023a-e6ce-452a-a71d-72841075d1ec)

Is this connected to taints / restrictions / node-selectors or to some nvidia-device-plugin not allowing to schedule / occupying master nodes?
