### ISSUE TITLE
Deployment of models stuck at progressing

### ISSUE THREAD

**Issue by cesarpferreira** [nekomeowww/ollama-operator#36]
Hi,

I am trying to deploying the model `llama3.3` as follows:

```yaml
apiVersion: ollama.ayaka.io/v1
kind: Model
metadata:
  name: llama3.3
spec:
  replicas: 1
  image: llama3.3
  imagePullPolicy: IfNotPresent
  storageClassName: nfs-csi
  # If you have your own PersistentVolumeClaim created
  persistentVolumeClaim: 
    claimName: llama3-3-pvc
```

In the pod logs the image is pulled and in the end it gives the following error:

```bash
[ollama-image-pull] 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
75 100 42 100 33 23622 18560 --:--:-- --:--:-- --:--:-- 75000
{"error":"model '%!s(MISSING)' not found"}
```
It looks like the Arguments for the pod are wrongly generated:

![image](https://github.com/user-attachments/assets/09ae0a6a-9e0d-4ee0-be3b-ec1ac61bb57e)

While looking on the repository for possible causes I noticed in https://github.com/nekomeowww/ollama-operator/blob/f01a3c54c3ebae2fc94e2e78b16033a8e5fbd7ce/pkg/model/pod.go#L181 and https://github.com/nekomeowww/ollama-operator/blob/f01a3c54c3ebae2fc94e2e78b16033a8e5fbd7ce/pkg/model/pod.go#L207 there is a `+` instead of a `,` right before the `image` var.

This is causing the pod to use `Model` name for the image name and not filling with the model name in json for the curl. After pulling the model the resource deployment gets stuck and the service is not created.
