### ISSUE TITLE
model name  and  images path

### ISSUE THREAD

**Issue by taikai-zz** [nekomeowww/ollama-operator#39]
kollama deploy phi --image=https://registry.ollama.ai/library/deepseek-r1:32b
Although this is a problematic command, it can still start

![Image](https://github.com/user-attachments/assets/43491575-54b0-49b5-9e0b-9f85f4b8be66)

Set the model name and then set the images path. The commands in the initialized container can only download the latest of the model name,

Is there a problem with parameter passing when starting the init container command

**Comment by nekomeowww** [comment]
Oh. Nice catch. Let me fix it.

**Comment by dotbalo** [comment]
Is this issue fixed? I can't specify a tag for the model I deployed using the operator. For example, I used the following template to deploy a deepseek-r1:1.5b model, but the default 7B was actually deployed.
````
apiVersion: ollama.ayaka.io/v1
kind: Model
metadata:
  name: deepseek-r1
spec:
  image: deepseek-r1:1.5b
  storageClassName: mdx-local-path 
  replicas: 2
  imagePullPolicy: IfNotPresent
````
The logs printed by the created Pod are as follows:
````
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = Q4_K - Medium
llm_load_print_meta: model params     = 7.62 B
llm_load_print_meta: model size       = 4.36 GiB (4.91 BPW) 
llm_load_print_meta: general.name     = DeepSeek R1 Distill Qwen 7B
````
