### ISSUE TITLE
Problem with ollama models with paths/slashes

### ISSUE THREAD

**Issue by Kr0n0** [nekomeowww/ollama-operator#65]
Hi @nekomeowww,

I have been testing ollama-operator for a k3s cluster with GPU and GPU Timeslice support, using the CRDs for model deployment, but I've had a problem with certain models:

## Models like qwen2.5-coder:7b worked ok

```yaml
apiVersion: ollama.ayaka.io/v1
kind: Model
metadata:
  name: qwen2.5-coder-7b
  namespace: default
spec:
  replicas: 1
  image: qwen2.5-coder:7b
  imagePullPolicy: IfNotPresent
  # Storage
  storageClassName: local-path
  persistentVolumeClaim: 
    claimName: ollama-models
    readOnly: false
  persistentVolume:
    accessMode: ReadWriteOnce
  # GPU Support
  runtimeClassName: nvidia
  extraEnv:
    - name: NVIDIA_VISIBLE_DEVICES
      value: all
  resources:
    limits:
      nvidia.com/gpu: 1
    requests:
      nvidia.com/gpu: 1
```

### Container logs (ollama-image-pull)

```log
[...]
{"model":"qwen2.5-coder:7b","created_at":"2025-04-04T08:11:37.769149705Z","response":"","done":true,"done_reason":"load"}
```

### Container logs (server)

```log
[...]
2025/04/04 08:11:40 routes.go:1231: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_CONTEXT_LENGTH:2048 OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://0.0.0.0:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_KV_CACHE_TYPE: OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:/root/.ollama/models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NEW_ENGINE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://* vscode-file://*] OLLAMA_SCHED_SPREAD:false ROCR_VISIBLE_DEVICES: http_proxy: https_proxy: no_proxy:]"
time=2025-04-04T08:11:40.433Z level=INFO source=images.go:458 msg="total blobs: 14"
time=2025-04-04T08:11:40.433Z level=INFO source=images.go:465 msg="total unused blobs removed: 0"
time=2025-04-04T08:11:40.433Z level=INFO source=routes.go:1298 msg="Listening on [::]:11434 (version 0.6.4)"
time=2025-04-04T08:11:40.433Z level=INFO source=gpu.go:217 msg="looking for compatible GPUs"
time=2025-04-04T08:11:40.576Z level=INFO source=types.go:130 msg="inference compute" id=GPU-e67afa31-2f7e-eeb9-edb4-99424a760d93 library=cuda variant=v12 compute=8.6 driver=12.8 name="NVIDIA GeForce RTX 3080 Laptop GPU" total="15.8 GiB" available="14.4 GiB"
[...]
```

## Models with slashes/paths within the ollama repository (such as tazarov/all-minilm-l6-v2-f32:latest)

```yaml
apiVersion: ollama.ayaka.io/v1
kind: Model
metadata:
  name: tazarov-all-minilm-l6-v2-f32
  namespace: default
spec:
  replicas: 1
  image: tazarov/all-minilm-l6-v2-f32:latest
  imagePullPolicy: IfNotPresent
  # Storage
  storageClassName: local-path
  persistentVolumeClaim: 
    claimName: ollama-models
    readOnly: false
  persistentVolume:
    accessMode: ReadWriteOnce
  # GPU Support
  runtimeClassName: nvidia
  extraEnv:
    - name: NVIDIA_VISIBLE_DEVICES
      value: all
  resources:
    limits:
      nvidia.com/gpu: 1
    requests:
      nvidia.com/gpu: 1
```

### Container logs (ollama-image-pull)

```log
[...]
{"error":"model 'all-minilm-l6-v2-f32' not found"}
```

### Container logs (server)

```log
[...]
2025/04/04 08:25:58 routes.go:1231: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_CONTEXT_LENGTH:2048 OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://0.0.0.0:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_KV_CACHE_TYPE: OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:/root/.ollama/models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NEW_ENGINE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://* vscode-file://*] OLLAMA_SCHED_SPREAD:false ROCR_VISIBLE_DEVICES: http_proxy: https_proxy: no_proxy:]"
time=2025-04-04T08:25:58.374Z level=INFO source=images.go:458 msg="total blobs: 14"
time=2025-04-04T08:25:58.374Z level=INFO source=images.go:465 msg="total unused blobs removed: 0"
time=2025-04-04T08:25:58.374Z level=INFO source=routes.go:1298 msg="Listening on [::]:11434 (version 0.6.4)"
time=2025-04-04T08:25:58.374Z level=INFO source=gpu.go:217 msg="looking for compatible GPUs"
time=2025-04-04T08:25:58.450Z level=INFO source=types.go:130 msg="inference compute" id=GPU-e67afa31-2f7e-eeb9-edb4-99424a760d93 library=cuda variant=v12 compute=8.6 driver=12.8 name="NVIDIA GeForce RTX 3080 Laptop GPU" total="15.8 GiB" available="14.2 GiB"
[...]
```

As I understand, it may be because of the slash in the metadata.name (that I had to replace). Maybe it is related to https://github.com/nekomeowww/ollama-operator/issues/39 or https://github.com/nekomeowww/ollama-operator/issues/21.
