### ISSUE TITLE
podTemplate doesnt allow to change ollama image

### ISSUE THREAD

**Issue by sebt3** [nekomeowww/ollama-operator#77]
Hello,

Using the following model :
```
apiVersion: ollama.ayaka.io/v1
kind: Model
metadata:
  name: phi
spec:
  image: phi
  podTemplate:
    spec:
      containers:
      - name: server
        image: ollama/ollama:rocm
```
I'm still getting a pod using `ollama/ollama:latest` which, obviously is not the desired situation.
Is there a way to activate AMD GPU acceleration beside this ?
