### ISSUE TITLE
model.spec.extraEnv doesn't work

### ISSUE THREAD

**Issue by Slach** [nekomeowww/ollama-operator#81]
I tried the following manifest:
```
apiVersion: ollama.ayaka.io/v1                                                                                                                                                                           kind: Model                                                                                                                                                                                              metadata:                                                                                                                                                                                                  
  name: granite
  namespace: ollama-operator-system                                                                                                                                                                        spec:
  extraEnv:
  - name: OLLAMA_API_KEY
    value: test-key
  image: granite-embedding:278m                                                                                                                                                                          
```
but don't see anything in `env` section for deployed ollama containers
